services:
  postgres:
    build:
      context: ..
      dockerfile: .ddev/Dockerfile.postgres
    container_name: ddev-ai-document-system-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_documents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ../database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_documents"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default

volumes:
  pgvector_data:
    driver: local

networks:
  default:
    external: true
    name: ddev_default
